// Class: ReadPyKeras
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : PyKeras::PyKeras
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.25/01       [399617]
Creator        : sanjiban
Date           : Tue Jul 20 03:08:54 2021
Host           : Linux sanjiban-HP-Notebook-PC 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /media/sanjiban/Applications1/GSoC21/root-fork/root/tmva/pymva/test
Training events: 400
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "D,G" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
FilenameModel: "kerasModelMulticlass.h5" [Filename of the initial Keras model]
FilenameTrainedModel: "trainedKerasModelMulticlass.h5" [Filename of the trained output Keras model]
BatchSize: "32" [Training batch size]
NumEpochs: "20" [Number of training epochs]
Verbose: "0" [Keras verbosity during training]
SaveBestOnly: "False" [Store only weights with smallest validation loss]
# Default:
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
NumThreads: "0" [Number of CPU threads (only for Tensorflow backend)]
GpuOptions: "" [GPU options for tensorflow, such as allow_growth]
tf.keras: "True" [Use tensorflow from Keras]
ContinueTraining: "False" [Load weights from previous training]
TriesEarlyStopping: "-1" [Number of epochs with no improvement in validation loss after which training will be stopped. The default or a negative number deactivates this option.]
LearningRateSchedule: "" [Set new learning rate during training at specific epochs, e.g., "50,0.01;70,0.005"]
TensorBoard: "" [Write a log during training to visualize and monitor the training performance with TensorBoard]
ValidationSize: "20%" [Part of the training data to use for validation. Specify as 0.2 or 20% to use a fifth of the data set as validation set. Specify as 100 to use exactly 100 events. (Default: 20%)]
UserCode: "" [Optional python code provided by the user to be executed before loading the Keras model]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
var1                          var1                          var1                          var1                                                            'F'    [-3.11500716209,2.28524398804]
var2                          var2                          var2                          var2                                                            'F'    [-3.69520401955,3.111307621]
var3                          var3                          var3                          var3                                                            'F'    [-3.3587179184,3.97955369949]
var4                          var4                          var4                          var4                                                            'F'    [-3.79127573967,4.11785364151]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual std::vector<double> GetMulticlassValues( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadPyKeras : public IClassifierReader {

 public:

   // constructor
   ReadPyKeras( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadPyKeras" ),
        fNvars( 4 )
   {
      // the training input variables
      const char* inputVars[] = { "var1", "var2", "var3", "var4" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -2.10036492347717;
      fVmax[0] = 5.73072862625122;
      fVmin[1] = -2.10036873817444;
      fVmax[1] = 5.73072862625122;
      fVmin[2] = -2.10027837753296;
      fVmax[2] = 5.73072862625122;
      fVmin[3] = -2.10034704208374;
      fVmax[3] = 5.73072862625122;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadPyKeras() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   std::vector<double> GetMulticlassValues( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fDecTF_1[5][4][4];

   int nvar;

   double  cumulativeDist[4][5][42];
   double  X[4][5][42];
   double xMin[4][5];
   double xMax[4][5];
   int    nbins[4][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform_2();
   void Transform_2( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   std::vector<double> GetMulticlassValues__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
inline std::vector<double> ReadPyKeras::GetMulticlassValues( const std::vector<double>& inputValues ) const
{
   // classifier response value
   std::vector<double> retval;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMulticlassValues__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadPyKeras::InitTransform_1()
{
   // Decorrelation transformation, initialisation
   fDecTF_1[0][0][0] = 1.89321770787;
   fDecTF_1[0][0][1] = 0.423097995746;
   fDecTF_1[0][0][2] = -0.0132961381823;
   fDecTF_1[0][0][3] = -1.35514124342;
   fDecTF_1[0][1][0] = 0.423097995746;
   fDecTF_1[0][1][1] = 1.55509410249;
   fDecTF_1[0][1][2] = -0.321912075479;
   fDecTF_1[0][1][3] = -0.906131634461;
   fDecTF_1[0][2][0] = -0.0132961381823;
   fDecTF_1[0][2][1] = -0.321912075479;
   fDecTF_1[0][2][2] = 1.68161214096;
   fDecTF_1[0][2][3] = -0.770553815687;
   fDecTF_1[0][3][0] = -1.35514124342;
   fDecTF_1[0][3][1] = -0.906131634461;
   fDecTF_1[0][3][2] = -0.770553815687;
   fDecTF_1[0][3][3] = 2.97831896146;
   fDecTF_1[1][0][0] = 1.76046731501;
   fDecTF_1[1][0][1] = 0.33801976201;
   fDecTF_1[1][0][2] = 0.0302476842183;
   fDecTF_1[1][0][3] = -1.20448337515;
   fDecTF_1[1][1][0] = 0.33801976201;
   fDecTF_1[1][1][1] = 1.61908046109;
   fDecTF_1[1][1][2] = -0.455480190271;
   fDecTF_1[1][1][3] = -0.791173872092;
   fDecTF_1[1][2][0] = 0.0302476842183;
   fDecTF_1[1][2][1] = -0.455480190271;
   fDecTF_1[1][2][2] = 1.87540346717;
   fDecTF_1[1][2][3] = -0.778092115271;
   fDecTF_1[1][3][0] = -1.20448337515;
   fDecTF_1[1][3][1] = -0.791173872092;
   fDecTF_1[1][3][2] = -0.778092115271;
   fDecTF_1[1][3][3] = 2.83366988665;
   fDecTF_1[2][0][0] = 1.92967561804;
   fDecTF_1[2][0][1] = 0.452070890603;
   fDecTF_1[2][0][2] = -0.00942395731259;
   fDecTF_1[2][0][3] = -1.42157495833;
   fDecTF_1[2][1][0] = 0.452070890603;
   fDecTF_1[2][1][1] = 1.63518858757;
   fDecTF_1[2][1][2] = -0.303296433924;
   fDecTF_1[2][1][3] = -0.937184952557;
   fDecTF_1[2][2][0] = -0.00942395731259;
   fDecTF_1[2][2][1] = -0.303296433924;
   fDecTF_1[2][2][2] = 1.78441422485;
   fDecTF_1[2][2][3] = -0.818383102079;
   fDecTF_1[2][3][0] = -1.42157495833;
   fDecTF_1[2][3][1] = -0.937184952557;
   fDecTF_1[2][3][2] = -0.818383102079;
   fDecTF_1[2][3][3] = 3.07566226542;
   fDecTF_1[3][0][0] = 1.53802659875;
   fDecTF_1[3][0][1] = 0.579355135851;
   fDecTF_1[3][0][2] = -0.0703580803065;
   fDecTF_1[3][0][3] = -0.131114468064;
   fDecTF_1[3][1][0] = 0.579355135851;
   fDecTF_1[3][1][1] = 1.72275596134;
   fDecTF_1[3][1][2] = 0.00725116893677;
   fDecTF_1[3][1][3] = -0.000202480171279;
   fDecTF_1[3][2][0] = -0.0703580803065;
   fDecTF_1[3][2][1] = 0.00725116893677;
   fDecTF_1[3][2][2] = 0.894161819633;
   fDecTF_1[3][2][3] = 0.0123912115795;
   fDecTF_1[3][3][0] = -0.131114468064;
   fDecTF_1[3][3][1] = -0.000202480171279;
   fDecTF_1[3][3][2] = 0.0123912115795;
   fDecTF_1[3][3][3] = 0.900972880828;
   fDecTF_1[4][0][0] = 1.33182476934;
   fDecTF_1[4][0][1] = 0.0550164025109;
   fDecTF_1[4][0][2] = -0.123543434466;
   fDecTF_1[4][0][3] = -0.423988171494;
   fDecTF_1[4][1][0] = 0.0550164025109;
   fDecTF_1[4][1][1] = 1.12085722341;
   fDecTF_1[4][1][2] = -0.210129239308;
   fDecTF_1[4][1][3] = -0.26070632771;
   fDecTF_1[4][2][0] = -0.123543434466;
   fDecTF_1[4][2][1] = -0.210129239308;
   fDecTF_1[4][2][2] = 1.0645632249;
   fDecTF_1[4][2][3] = -0.201743669019;
   fDecTF_1[4][3][0] = -0.423988171494;
   fDecTF_1[4][3][1] = -0.26070632771;
   fDecTF_1[4][3][2] = -0.201743669019;
   fDecTF_1[4][3][3] = 1.16325689113;
}

//_______________________________________________________________________
inline void ReadPyKeras::Transform_1( std::vector<double>& iv, int cls) const
{
   // Decorrelation transformation
   if (cls < 0 || cls > 4) {
       if (4 > 1 ) cls = 4;
       else cls = 2;
   }

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
   }

   std::vector<double> tv;
   for (int i=0; i<4;i++) {
      double v = 0;
      for (int j=0; j<4; j++)
         v += iv[indicesGet.at(j)] * fDecTF_1[cls][i][j];
      tv.push_back(v);
   }
   for (int i=0; i<4;i++) iv[indicesPut.at(i)] = tv[i];
}

#include "math.h"

//_______________________________________________________________________
inline void ReadPyKeras::InitTransform_2()
{
   // Gauss/Uniform transformation, initialisation
   nvar=4;
   nbins[0][0]=11;
   nbins[1][0]=11;
   nbins[2][0]=11;
   nbins[3][0]=11;
   nbins[0][1]=11;
   nbins[1][1]=11;
   nbins[2][1]=11;
   nbins[3][1]=11;
   nbins[0][2]=11;
   nbins[1][2]=11;
   nbins[2][2]=11;
   nbins[3][2]=11;
   nbins[0][3]=11;
   nbins[1][3]=11;
   nbins[2][3]=11;
   nbins[3][3]=11;
   nbins[0][4]=41;
   nbins[1][4]=41;
   nbins[2][4]=41;
   nbins[3][4]=41;
    xMin[0][0]=-2.97257197e+00;
    xMax[0][0]=1.48863786e+00;
  cumulativeDist[0][0][0]=6.82352930e-02;
  X[0][0][0]=-2.97257197e+00;
  cumulativeDist[0][0][1]=1.52941182e-01;
  X[0][0][1]=-2.15385115e+00;
  cumulativeDist[0][0][2]=2.46470585e-01;
  X[0][0][2]=-1.22335392e+00;
  cumulativeDist[0][0][3]=3.41176480e-01;
  X[0][0][3]=-9.54214931e-01;
  cumulativeDist[0][0][4]=4.35294122e-01;
  X[0][0][4]=-6.29803553e-01;
  cumulativeDist[0][0][5]=5.29411793e-01;
  X[0][0][5]=-3.36393781e-01;
  cumulativeDist[0][0][6]=6.23529434e-01;
  X[0][0][6]=-1.19239552e-01;
  cumulativeDist[0][0][7]=7.17647076e-01;
  X[0][0][7]=1.06420519e-01;
  cumulativeDist[0][0][8]=8.11764717e-01;
  X[0][0][8]=4.22704063e-01;
  cumulativeDist[0][0][9]=9.05882359e-01;
  X[0][0][9]=8.73310357e-01;
  cumulativeDist[0][0][10]=1.00000000e+00;
  X[0][0][10]=1.48863786e+00;
    xMin[1][0]=-2.49554026e+00;
    xMax[1][0]=1.67924690e+00;
  cumulativeDist[1][0][0]=6.82352930e-02;
  X[1][0][0]=-2.49554026e+00;
  cumulativeDist[1][0][1]=1.52941182e-01;
  X[1][0][1]=-1.81333768e+00;
  cumulativeDist[1][0][2]=2.46470585e-01;
  X[1][0][2]=-9.78094816e-01;
  cumulativeDist[1][0][3]=3.41176480e-01;
  X[1][0][3]=-7.14729488e-01;
  cumulativeDist[1][0][4]=4.35294122e-01;
  X[1][0][4]=-4.65845928e-01;
  cumulativeDist[1][0][5]=5.29411793e-01;
  X[1][0][5]=-1.83703631e-01;
  cumulativeDist[1][0][6]=6.23529434e-01;
  X[1][0][6]=9.82881710e-02;
  cumulativeDist[1][0][7]=7.17647076e-01;
  X[1][0][7]=3.78775217e-01;
  cumulativeDist[1][0][8]=8.11764717e-01;
  X[1][0][8]=6.76732779e-01;
  cumulativeDist[1][0][9]=9.05882359e-01;
  X[1][0][9]=9.55004990e-01;
  cumulativeDist[1][0][10]=1.00000000e+00;
  X[1][0][10]=1.67924690e+00;
    xMin[2][0]=-1.39767855e+00;
    xMax[2][0]=2.01512545e+00;
  cumulativeDist[2][0][0]=6.82352930e-02;
  X[2][0][0]=-1.39767855e+00;
  cumulativeDist[2][0][1]=1.52941182e-01;
  X[2][0][1]=-9.54668224e-01;
  cumulativeDist[2][0][2]=2.46470585e-01;
  X[2][0][2]=-3.27337027e-01;
  cumulativeDist[2][0][3]=3.41176480e-01;
  X[2][0][3]=-5.83780920e-02;
  cumulativeDist[2][0][4]=4.35294122e-01;
  X[2][0][4]=9.99118844e-02;
  cumulativeDist[2][0][5]=5.29411793e-01;
  X[2][0][5]=2.68267162e-01;
  cumulativeDist[2][0][6]=6.23529434e-01;
  X[2][0][6]=4.34592068e-01;
  cumulativeDist[2][0][7]=7.17647076e-01;
  X[2][0][7]=5.90759963e-01;
  cumulativeDist[2][0][8]=8.11764717e-01;
  X[2][0][8]=7.68503755e-01;
  cumulativeDist[2][0][9]=9.05882359e-01;
  X[2][0][9]=1.11550927e+00;
  cumulativeDist[2][0][10]=1.00000000e+00;
  X[2][0][10]=2.01512545e+00;
    xMin[3][0]=-5.43346941e-01;
    xMax[3][0]=1.99410945e+00;
  cumulativeDist[3][0][0]=6.82352930e-02;
  X[3][0][0]=-5.43346941e-01;
  cumulativeDist[3][0][1]=1.52941182e-01;
  X[3][0][1]=-2.12575570e-01;
  cumulativeDist[3][0][2]=2.46470585e-01;
  X[3][0][2]=2.59362236e-01;
  cumulativeDist[3][0][3]=3.41176480e-01;
  X[3][0][3]=4.64438230e-01;
  cumulativeDist[3][0][4]=4.35294122e-01;
  X[3][0][4]=5.84514558e-01;
  cumulativeDist[3][0][5]=5.29411793e-01;
  X[3][0][5]=7.16858804e-01;
  cumulativeDist[3][0][6]=6.23529434e-01;
  X[3][0][6]=9.07608688e-01;
  cumulativeDist[3][0][7]=7.17647076e-01;
  X[3][0][7]=1.06354624e+00;
  cumulativeDist[3][0][8]=8.11764717e-01;
  X[3][0][8]=1.17056757e+00;
  cumulativeDist[3][0][9]=9.05882359e-01;
  X[3][0][9]=1.35630184e+00;
  cumulativeDist[3][0][10]=1.00000000e+00;
  X[3][0][10]=1.99410945e+00;
    xMin[0][1]=-2.77878606e+00;
    xMax[0][1]=1.82617027e+00;
  cumulativeDist[0][1][0]=6.82352930e-02;
  X[0][1][0]=-2.77878606e+00;
  cumulativeDist[0][1][1]=1.52941182e-01;
  X[0][1][1]=-1.99015933e+00;
  cumulativeDist[0][1][2]=2.46470585e-01;
  X[0][1][2]=-9.50474232e-01;
  cumulativeDist[0][1][3]=3.41176480e-01;
  X[0][1][3]=-5.52628607e-01;
  cumulativeDist[0][1][4]=4.35294122e-01;
  X[0][1][4]=-2.29428038e-01;
  cumulativeDist[0][1][5]=5.29411793e-01;
  X[0][1][5]=2.63745487e-02;
  cumulativeDist[0][1][6]=6.23529434e-01;
  X[0][1][6]=2.04424396e-01;
  cumulativeDist[0][1][7]=7.17647076e-01;
  X[0][1][7]=4.14458781e-01;
  cumulativeDist[0][1][8]=8.11764717e-01;
  X[0][1][8]=6.62071168e-01;
  cumulativeDist[0][1][9]=9.05882359e-01;
  X[0][1][9]=1.00376841e+00;
  cumulativeDist[0][1][10]=1.00000000e+00;
  X[0][1][10]=1.82617027e+00;
    xMin[1][1]=-2.58887279e+00;
    xMax[1][1]=1.58316725e+00;
  cumulativeDist[1][1][0]=6.82352930e-02;
  X[1][1][0]=-2.58887279e+00;
  cumulativeDist[1][1][1]=1.52941182e-01;
  X[1][1][1]=-1.86943626e+00;
  cumulativeDist[1][1][2]=2.46470585e-01;
  X[1][1][2]=-1.01096180e+00;
  cumulativeDist[1][1][3]=3.41176480e-01;
  X[1][1][3]=-7.41907328e-01;
  cumulativeDist[1][1][4]=4.35294122e-01;
  X[1][1][4]=-4.40719351e-01;
  cumulativeDist[1][1][5]=5.29411793e-01;
  X[1][1][5]=-1.70707867e-01;
  cumulativeDist[1][1][6]=6.23529434e-01;
  X[1][1][6]=5.78920692e-02;
  cumulativeDist[1][1][7]=7.17647076e-01;
  X[1][1][7]=3.07586998e-01;
  cumulativeDist[1][1][8]=8.11764717e-01;
  X[1][1][8]=5.16311035e-01;
  cumulativeDist[1][1][9]=9.05882359e-01;
  X[1][1][9]=7.91835725e-01;
  cumulativeDist[1][1][10]=1.00000000e+00;
  X[1][1][10]=1.58316725e+00;
    xMin[2][1]=-1.98413152e+00;
    xMax[2][1]=1.26225975e+00;
  cumulativeDist[2][1][0]=6.82352930e-02;
  X[2][1][0]=-1.98413152e+00;
  cumulativeDist[2][1][1]=1.52941182e-01;
  X[2][1][1]=-1.55076289e+00;
  cumulativeDist[2][1][2]=2.46470585e-01;
  X[2][1][2]=-9.38219756e-01;
  cumulativeDist[2][1][3]=3.41176480e-01;
  X[2][1][3]=-6.89586312e-01;
  cumulativeDist[2][1][4]=4.35294122e-01;
  X[2][1][4]=-5.45032591e-01;
  cumulativeDist[2][1][5]=5.29411793e-01;
  X[2][1][5]=-4.24953938e-01;
  cumulativeDist[2][1][6]=6.23529434e-01;
  X[2][1][6]=-2.75075644e-01;
  cumulativeDist[2][1][7]=7.17647076e-01;
  X[2][1][7]=-1.19328972e-01;
  cumulativeDist[2][1][8]=8.11764717e-01;
  X[2][1][8]=4.36517037e-02;
  cumulativeDist[2][1][9]=9.05882359e-01;
  X[2][1][9]=3.20993811e-01;
  cumulativeDist[2][1][10]=1.00000000e+00;
  X[2][1][10]=1.26225975e+00;
    xMin[3][1]=-1.76046973e+00;
    xMax[3][1]=5.76272346e-01;
  cumulativeDist[3][1][0]=6.82352930e-02;
  X[3][1][0]=-1.76046973e+00;
  cumulativeDist[3][1][1]=1.52941182e-01;
  X[3][1][1]=-1.45805812e+00;
  cumulativeDist[3][1][2]=2.46470585e-01;
  X[3][1][2]=-1.02426475e+00;
  cumulativeDist[3][1][3]=3.41176480e-01;
  X[3][1][3]=-7.98022300e-01;
  cumulativeDist[3][1][4]=4.35294122e-01;
  X[3][1][4]=-6.42129302e-01;
  cumulativeDist[3][1][5]=5.29411793e-01;
  X[3][1][5]=-5.13399646e-01;
  cumulativeDist[3][1][6]=6.23529434e-01;
  X[3][1][6]=-3.27241994e-01;
  cumulativeDist[3][1][7]=7.17647076e-01;
  X[3][1][7]=-1.50794741e-01;
  cumulativeDist[3][1][8]=8.11764717e-01;
  X[3][1][8]=-3.52398399e-02;
  cumulativeDist[3][1][9]=9.05882359e-01;
  X[3][1][9]=1.13192545e-01;
  cumulativeDist[3][1][10]=1.00000000e+00;
  X[3][1][10]=5.76272346e-01;
    xMin[0][2]=-2.86931980e+00;
    xMax[0][2]=1.78532404e+00;
  cumulativeDist[0][2][0]=6.82352930e-02;
  X[0][2][0]=-2.86931980e+00;
  cumulativeDist[0][2][1]=1.52941182e-01;
  X[0][2][1]=-2.08098018e+00;
  cumulativeDist[0][2][2]=2.46470585e-01;
  X[0][2][2]=-1.04129502e+00;
  cumulativeDist[0][2][3]=3.41176480e-01;
  X[0][2][3]=-6.54172719e-01;
  cumulativeDist[0][2][4]=4.35294122e-01;
  X[0][2][4]=-3.00895479e-01;
  cumulativeDist[0][2][5]=5.29411793e-01;
  X[0][2][5]=-7.07520172e-03;
  cumulativeDist[0][2][6]=6.23529434e-01;
  X[0][2][6]=1.25667542e-01;
  cumulativeDist[0][2][7]=7.17647076e-01;
  X[0][2][7]=3.36213157e-01;
  cumulativeDist[0][2][8]=8.11764717e-01;
  X[0][2][8]=6.25490248e-01;
  cumulativeDist[0][2][9]=9.05882359e-01;
  X[0][2][9]=9.89356399e-01;
  cumulativeDist[0][2][10]=1.00000000e+00;
  X[0][2][10]=1.78532404e+00;
    xMin[1][2]=-2.12648737e+00;
    xMax[1][2]=2.04555225e+00;
  cumulativeDist[1][2][0]=6.82352930e-02;
  X[1][2][0]=-2.12648737e+00;
  cumulativeDist[1][2][1]=1.52941182e-01;
  X[1][2][1]=-1.40295449e+00;
  cumulativeDist[1][2][2]=2.46470585e-01;
  X[1][2][2]=-4.53832738e-01;
  cumulativeDist[1][2][3]=3.41176480e-01;
  X[1][2][3]=-9.81604997e-02;
  cumulativeDist[1][2][4]=4.35294122e-01;
  X[1][2][4]=1.25426447e-01;
  cumulativeDist[1][2][5]=5.29411793e-01;
  X[1][2][5]=2.84102567e-01;
  cumulativeDist[1][2][6]=6.23529434e-01;
  X[1][2][6]=4.83611792e-01;
  cumulativeDist[1][2][7]=7.17647076e-01;
  X[1][2][7]=8.09440285e-01;
  cumulativeDist[1][2][8]=8.11764717e-01;
  X[1][2][8]=1.05129707e+00;
  cumulativeDist[1][2][9]=9.05882359e-01;
  X[1][2][9]=1.27130926e+00;
  cumulativeDist[1][2][10]=1.00000000e+00;
  X[1][2][10]=2.04555225e+00;
    xMin[2][2]=-8.61986518e-01;
    xMax[2][2]=2.20465201e+00;
  cumulativeDist[2][2][0]=6.82352930e-02;
  X[2][2][0]=-8.61986518e-01;
  cumulativeDist[2][2][1]=1.52941182e-01;
  X[2][2][1]=-4.64360196e-01;
  cumulativeDist[2][2][2]=2.46470585e-01;
  X[2][2][2]=5.15292399e-02;
  cumulativeDist[2][2][3]=3.41176480e-01;
  X[2][2][3]=2.74042606e-01;
  cumulativeDist[2][2][4]=4.35294122e-01;
  X[2][2][4]=4.51944768e-01;
  cumulativeDist[2][2][5]=5.29411793e-01;
  X[2][2][5]=6.35417730e-01;
  cumulativeDist[2][2][6]=6.23529434e-01;
  X[2][2][6]=8.16792041e-01;
  cumulativeDist[2][2][7]=7.17647076e-01;
  X[2][2][7]=9.71689701e-01;
  cumulativeDist[2][2][8]=8.11764717e-01;
  X[2][2][8]=1.10941756e+00;
  cumulativeDist[2][2][9]=9.05882359e-01;
  X[2][2][9]=1.44817346e+00;
  cumulativeDist[2][2][10]=1.00000000e+00;
  X[2][2][10]=2.20465201e+00;
    xMin[3][2]=-2.11863697e+00;
    xMax[3][2]=4.29824323e-01;
  cumulativeDist[3][2][0]=6.82352930e-02;
  X[3][2][0]=-2.11863697e+00;
  cumulativeDist[3][2][1]=1.52941182e-01;
  X[3][2][1]=-1.78734410e+00;
  cumulativeDist[3][2][2]=2.46470585e-01;
  X[3][2][2]=-1.32541734e+00;
  cumulativeDist[3][2][3]=3.41176480e-01;
  X[3][2][3]=-1.08537939e+00;
  cumulativeDist[3][2][4]=4.35294122e-01;
  X[3][2][4]=-9.48972672e-01;
  cumulativeDist[3][2][5]=5.29411793e-01;
  X[3][2][5]=-8.29006463e-01;
  cumulativeDist[3][2][6]=6.23529434e-01;
  X[3][2][6]=-6.35420322e-01;
  cumulativeDist[3][2][7]=7.17647076e-01;
  X[3][2][7]=-4.85135660e-01;
  cumulativeDist[3][2][8]=8.11764717e-01;
  X[3][2][8]=-3.63881782e-01;
  cumulativeDist[3][2][9]=9.05882359e-01;
  X[3][2][9]=-1.35805606e-01;
  cumulativeDist[3][2][10]=1.00000000e+00;
  X[3][2][10]=4.29824323e-01;
    xMin[0][3]=-1.49730486e+00;
    xMax[0][3]=2.37310034e+00;
  cumulativeDist[0][3][0]=6.82352930e-02;
  X[0][3][0]=-1.49730486e+00;
  cumulativeDist[0][3][1]=1.52941182e-01;
  X[0][3][1]=-1.28179312e+00;
  cumulativeDist[0][3][2]=2.46470585e-01;
  X[0][3][2]=-8.74943137e-01;
  cumulativeDist[0][3][3]=3.41176480e-01;
  X[0][3][3]=-4.70436335e-01;
  cumulativeDist[0][3][4]=4.35294122e-01;
  X[0][3][4]=-1.06424829e-01;
  cumulativeDist[0][3][5]=5.29411793e-01;
  X[0][3][5]=2.13127578e-01;
  cumulativeDist[0][3][6]=6.23529434e-01;
  X[0][3][6]=5.42320058e-01;
  cumulativeDist[0][3][7]=7.17647076e-01;
  X[0][3][7]=8.22321147e-01;
  cumulativeDist[0][3][8]=8.11764717e-01;
  X[0][3][8]=1.13110349e+00;
  cumulativeDist[0][3][9]=9.05882359e-01;
  X[0][3][9]=1.56933272e+00;
  cumulativeDist[0][3][10]=1.00000000e+00;
  X[0][3][10]=2.37310034e+00;
    xMin[1][3]=-1.68921274e+00;
    xMax[1][3]=2.19131553e+00;
  cumulativeDist[1][3][0]=6.82352930e-02;
  X[1][3][0]=-1.68921274e+00;
  cumulativeDist[1][3][1]=1.52941182e-01;
  X[1][3][1]=-9.58156683e-01;
  cumulativeDist[1][3][2]=2.46470585e-01;
  X[1][3][2]=1.39563195e-01;
  cumulativeDist[1][3][3]=3.41176480e-01;
  X[1][3][3]=7.09980458e-01;
  cumulativeDist[1][3][4]=4.35294122e-01;
  X[1][3][4]=1.06140327e+00;
  cumulativeDist[1][3][5]=5.29411793e-01;
  X[1][3][5]=1.28205794e+00;
  cumulativeDist[1][3][6]=6.23529434e-01;
  X[1][3][6]=1.42792565e+00;
  cumulativeDist[1][3][7]=7.17647076e-01;
  X[1][3][7]=1.58243722e+00;
  cumulativeDist[1][3][8]=8.11764717e-01;
  X[1][3][8]=1.70984715e+00;
  cumulativeDist[1][3][9]=9.05882359e-01;
  X[1][3][9]=1.87409556e+00;
  cumulativeDist[1][3][10]=1.00000000e+00;
  X[1][3][10]=2.19131553e+00;
    xMin[2][3]=-2.38827860e+00;
    xMax[2][3]=1.63825554e+00;
  cumulativeDist[2][3][0]=6.82352930e-02;
  X[2][3][0]=-2.38827860e+00;
  cumulativeDist[2][3][1]=1.52941182e-01;
  X[2][3][1]=-2.20461893e+00;
  cumulativeDist[2][3][2]=2.46470585e-01;
  X[2][3][2]=-1.90080082e+00;
  cumulativeDist[2][3][3]=3.41176480e-01;
  X[2][3][3]=-1.57175404e+00;
  cumulativeDist[2][3][4]=4.35294122e-01;
  X[2][3][4]=-1.20616513e+00;
  cumulativeDist[2][3][5]=5.29411793e-01;
  X[2][3][5]=-7.86315352e-01;
  cumulativeDist[2][3][6]=6.23529434e-01;
  X[2][3][6]=-3.79809156e-01;
  cumulativeDist[2][3][7]=7.17647076e-01;
  X[2][3][7]=-1.77105144e-02;
  cumulativeDist[2][3][8]=8.11764717e-01;
  X[2][3][8]=5.48334993e-01;
  cumulativeDist[2][3][9]=9.05882359e-01;
  X[2][3][9]=1.12150037e+00;
  cumulativeDist[2][3][10]=1.00000000e+00;
  X[2][3][10]=1.63825554e+00;
    xMin[3][3]=-2.75335634e+00;
    xMax[3][3]=1.87285095e+00;
  cumulativeDist[3][3][0]=6.82352930e-02;
  X[3][3][0]=-2.75335634e+00;
  cumulativeDist[3][3][1]=1.52941182e-01;
  X[3][3][1]=-2.35505199e+00;
  cumulativeDist[3][3][2]=2.46470585e-01;
  X[3][3][2]=-1.70393711e+00;
  cumulativeDist[3][3][3]=3.41176480e-01;
  X[3][3][3]=-1.22698838e+00;
  cumulativeDist[3][3][4]=4.35294122e-01;
  X[3][3][4]=-7.87945807e-01;
  cumulativeDist[3][3][5]=5.29411793e-01;
  X[3][3][5]=-2.13887550e-01;
  cumulativeDist[3][3][6]=6.23529434e-01;
  X[3][3][6]=3.35017078e-01;
  cumulativeDist[3][3][7]=7.17647076e-01;
  X[3][3][7]=6.60293311e-01;
  cumulativeDist[3][3][8]=8.11764717e-01;
  X[3][3][8]=9.19316351e-01;
  cumulativeDist[3][3][9]=9.05882359e-01;
  X[3][3][9]=1.27653283e+00;
  cumulativeDist[3][3][10]=1.00000000e+00;
  X[3][3][10]=1.87285095e+00;
    xMin[0][4]=-2.97257197e+00;
    xMax[0][4]=2.43301558e+00;
  cumulativeDist[0][4][0]=1.78461540e-02;
  X[0][4][0]=-2.97257197e+00;
  cumulativeDist[0][4][1]=3.99999991e-02;
  X[0][4][1]=-2.47520870e+00;
  cumulativeDist[0][4][2]=6.44615367e-02;
  X[0][4][2]=-1.78847605e+00;
  cumulativeDist[0][4][3]=8.92307684e-02;
  X[0][4][3]=-1.46711850e+00;
  cumulativeDist[0][4][4]=1.13846153e-01;
  X[0][4][4]=-1.26415408e+00;
  cumulativeDist[0][4][5]=1.38461545e-01;
  X[0][4][5]=-1.16304743e+00;
  cumulativeDist[0][4][6]=1.63076922e-01;
  X[0][4][6]=-1.08764112e+00;
  cumulativeDist[0][4][7]=1.87692314e-01;
  X[0][4][7]=-9.71339136e-01;
  cumulativeDist[0][4][8]=2.12307692e-01;
  X[0][4][8]=-8.70046109e-01;
  cumulativeDist[0][4][9]=2.36923084e-01;
  X[0][4][9]=-7.93105006e-01;
  cumulativeDist[0][4][10]=2.61538476e-01;
  X[0][4][10]=-7.00851977e-01;
  cumulativeDist[0][4][11]=2.86153853e-01;
  X[0][4][11]=-6.16043121e-01;
  cumulativeDist[0][4][12]=3.10769230e-01;
  X[0][4][12]=-5.38552642e-01;
  cumulativeDist[0][4][13]=3.35384607e-01;
  X[0][4][13]=-4.56971467e-01;
  cumulativeDist[0][4][14]=3.60000014e-01;
  X[0][4][14]=-3.74664262e-01;
  cumulativeDist[0][4][15]=3.84615391e-01;
  X[0][4][15]=-2.89681062e-01;
  cumulativeDist[0][4][16]=4.09230769e-01;
  X[0][4][16]=-2.03132398e-01;
  cumulativeDist[0][4][17]=4.33846146e-01;
  X[0][4][17]=-1.22937743e-01;
  cumulativeDist[0][4][18]=4.58461553e-01;
  X[0][4][18]=-6.81549124e-02;
  cumulativeDist[0][4][19]=4.83076930e-01;
  X[0][4][19]=-2.03203657e-02;
  cumulativeDist[0][4][20]=5.07692337e-01;
  X[0][4][20]=3.12621160e-02;
  cumulativeDist[0][4][21]=5.32307684e-01;
  X[0][4][21]=8.13976116e-02;
  cumulativeDist[0][4][22]=5.56923091e-01;
  X[0][4][22]=1.37570642e-01;
  cumulativeDist[0][4][23]=5.81538439e-01;
  X[0][4][23]=1.96200132e-01;
  cumulativeDist[0][4][24]=6.06153846e-01;
  X[0][4][24]=2.69903898e-01;
  cumulativeDist[0][4][25]=6.30769253e-01;
  X[0][4][25]=3.41218010e-01;
  cumulativeDist[0][4][26]=6.55384600e-01;
  X[0][4][26]=3.99213061e-01;
  cumulativeDist[0][4][27]=6.80000007e-01;
  X[0][4][27]=4.75863263e-01;
  cumulativeDist[0][4][28]=7.04615414e-01;
  X[0][4][28]=5.53301066e-01;
  cumulativeDist[0][4][29]=7.29230762e-01;
  X[0][4][29]=6.26693606e-01;
  cumulativeDist[0][4][30]=7.53846169e-01;
  X[0][4][30]=7.06888437e-01;
  cumulativeDist[0][4][31]=7.78461516e-01;
  X[0][4][31]=7.84497052e-01;
  cumulativeDist[0][4][32]=8.03076923e-01;
  X[0][4][32]=8.72463405e-01;
  cumulativeDist[0][4][33]=8.27692330e-01;
  X[0][4][33]=9.74284142e-01;
  cumulativeDist[0][4][34]=8.52307677e-01;
  X[0][4][34]=1.08193731e+00;
  cumulativeDist[0][4][35]=8.76923084e-01;
  X[0][4][35]=1.18057889e+00;
  cumulativeDist[0][4][36]=9.01538491e-01;
  X[0][4][36]=1.28221905e+00;
  cumulativeDist[0][4][37]=9.26153839e-01;
  X[0][4][37]=1.41064787e+00;
  cumulativeDist[0][4][38]=9.50769246e-01;
  X[0][4][38]=1.57799095e+00;
  cumulativeDist[0][4][39]=9.75384593e-01;
  X[0][4][39]=1.80424643e+00;
  cumulativeDist[0][4][40]=1.00000000e+00;
  X[0][4][40]=2.43301558e+00;
    xMin[1][4]=-2.58887279e+00;
    xMax[1][4]=2.32742584e+00;
  cumulativeDist[1][4][0]=1.78461540e-02;
  X[1][4][0]=-2.58887279e+00;
  cumulativeDist[1][4][1]=3.99999991e-02;
  X[1][4][1]=-2.05020684e+00;
  cumulativeDist[1][4][2]=6.44615367e-02;
  X[1][4][2]=-1.39636672e+00;
  cumulativeDist[1][4][3]=8.92307684e-02;
  X[1][4][3]=-1.19391912e+00;
  cumulativeDist[1][4][4]=1.13846153e-01;
  X[1][4][4]=-1.02753025e+00;
  cumulativeDist[1][4][5]=1.38461545e-01;
  X[1][4][5]=-9.03905302e-01;
  cumulativeDist[1][4][6]=1.63076922e-01;
  X[1][4][6]=-8.11505377e-01;
  cumulativeDist[1][4][7]=1.87692314e-01;
  X[1][4][7]=-7.21518278e-01;
  cumulativeDist[1][4][8]=2.12307692e-01;
  X[1][4][8]=-6.34979188e-01;
  cumulativeDist[1][4][9]=2.36923084e-01;
  X[1][4][9]=-5.34401864e-01;
  cumulativeDist[1][4][10]=2.61538476e-01;
  X[1][4][10]=-4.15022269e-01;
  cumulativeDist[1][4][11]=2.86153853e-01;
  X[1][4][11]=-2.96037443e-01;
  cumulativeDist[1][4][12]=3.10769230e-01;
  X[1][4][12]=-2.05678396e-01;
  cumulativeDist[1][4][13]=3.35384607e-01;
  X[1][4][13]=-1.50833741e-01;
  cumulativeDist[1][4][14]=3.60000014e-01;
  X[1][4][14]=-8.17749649e-02;
  cumulativeDist[1][4][15]=3.84615391e-01;
  X[1][4][15]=-2.50427984e-03;
  cumulativeDist[1][4][16]=4.09230769e-01;
  X[1][4][16]=5.73842172e-02;
  cumulativeDist[1][4][17]=4.33846146e-01;
  X[1][4][17]=1.40478812e-01;
  cumulativeDist[1][4][18]=4.58461553e-01;
  X[1][4][18]=2.16233805e-01;
  cumulativeDist[1][4][19]=4.83076930e-01;
  X[1][4][19]=2.86407016e-01;
  cumulativeDist[1][4][20]=5.07692337e-01;
  X[1][4][20]=3.62443179e-01;
  cumulativeDist[1][4][21]=5.32307684e-01;
  X[1][4][21]=4.19635504e-01;
  cumulativeDist[1][4][22]=5.56923091e-01;
  X[1][4][22]=4.83618721e-01;
  cumulativeDist[1][4][23]=5.81538439e-01;
  X[1][4][23]=5.49292684e-01;
  cumulativeDist[1][4][24]=6.06153846e-01;
  X[1][4][24]=6.09739244e-01;
  cumulativeDist[1][4][25]=6.30769253e-01;
  X[1][4][25]=7.09812313e-01;
  cumulativeDist[1][4][26]=6.55384600e-01;
  X[1][4][26]=8.35367143e-01;
  cumulativeDist[1][4][27]=6.80000007e-01;
  X[1][4][27]=9.04123813e-01;
  cumulativeDist[1][4][28]=7.04615414e-01;
  X[1][4][28]=9.63703364e-01;
  cumulativeDist[1][4][29]=7.29230762e-01;
  X[1][4][29]=1.04236579e+00;
  cumulativeDist[1][4][30]=7.53846169e-01;
  X[1][4][30]=1.13047892e+00;
  cumulativeDist[1][4][31]=7.78461516e-01;
  X[1][4][31]=1.22054744e+00;
  cumulativeDist[1][4][32]=8.03076923e-01;
  X[1][4][32]=1.28972274e+00;
  cumulativeDist[1][4][33]=8.27692330e-01;
  X[1][4][33]=1.33965665e+00;
  cumulativeDist[1][4][34]=8.52307677e-01;
  X[1][4][34]=1.39802366e+00;
  cumulativeDist[1][4][35]=8.76923084e-01;
  X[1][4][35]=1.48625231e+00;
  cumulativeDist[1][4][36]=9.01538491e-01;
  X[1][4][36]=1.59780723e+00;
  cumulativeDist[1][4][37]=9.26153839e-01;
  X[1][4][37]=1.70302337e+00;
  cumulativeDist[1][4][38]=9.50769246e-01;
  X[1][4][38]=1.81270683e+00;
  cumulativeDist[1][4][39]=9.75384593e-01;
  X[1][4][39]=1.94401848e+00;
  cumulativeDist[1][4][40]=1.00000000e+00;
  X[1][4][40]=2.32742584e+00;
    xMin[2][4]=-2.38827860e+00;
    xMax[2][4]=2.32428628e+00;
  cumulativeDist[2][4][0]=1.78461540e-02;
  X[2][4][0]=-2.38827860e+00;
  cumulativeDist[2][4][1]=3.99999991e-02;
  X[2][4][1]=-2.20461893e+00;
  cumulativeDist[2][4][2]=6.44615367e-02;
  X[2][4][2]=-1.91071570e+00;
  cumulativeDist[2][4][3]=8.92307684e-02;
  X[2][4][3]=-1.64270794e+00;
  cumulativeDist[2][4][4]=1.13846153e-01;
  X[2][4][4]=-1.38555634e+00;
  cumulativeDist[2][4][5]=1.38461545e-01;
  X[2][4][5]=-1.20841002e+00;
  cumulativeDist[2][4][6]=1.63076922e-01;
  X[2][4][6]=-1.02983606e+00;
  cumulativeDist[2][4][7]=1.87692314e-01;
  X[2][4][7]=-8.48807156e-01;
  cumulativeDist[2][4][8]=2.12307692e-01;
  X[2][4][8]=-7.34154701e-01;
  cumulativeDist[2][4][9]=2.36923084e-01;
  X[2][4][9]=-6.52837485e-01;
  cumulativeDist[2][4][10]=2.61538476e-01;
  X[2][4][10]=-5.57082176e-01;
  cumulativeDist[2][4][11]=2.86153853e-01;
  X[2][4][11]=-4.69074622e-01;
  cumulativeDist[2][4][12]=3.10769230e-01;
  X[2][4][12]=-4.11725447e-01;
  cumulativeDist[2][4][13]=3.35384607e-01;
  X[2][4][13]=-3.53283823e-01;
  cumulativeDist[2][4][14]=3.60000014e-01;
  X[2][4][14]=-2.62221478e-01;
  cumulativeDist[2][4][15]=3.84615391e-01;
  X[2][4][15]=-1.87905692e-01;
  cumulativeDist[2][4][16]=4.09230769e-01;
  X[2][4][16]=-1.25319280e-01;
  cumulativeDist[2][4][17]=4.33846146e-01;
  X[2][4][17]=-5.90651277e-02;
  cumulativeDist[2][4][18]=4.58461553e-01;
  X[2][4][18]=-5.03520295e-03;
  cumulativeDist[2][4][19]=4.83076930e-01;
  X[2][4][19]=5.10150623e-02;
  cumulativeDist[2][4][20]=5.07692337e-01;
  X[2][4][20]=1.05516069e-01;
  cumulativeDist[2][4][21]=5.32307684e-01;
  X[2][4][21]=1.52258001e-01;
  cumulativeDist[2][4][22]=5.56923091e-01;
  X[2][4][22]=1.90023251e-01;
  cumulativeDist[2][4][23]=5.81538439e-01;
  X[2][4][23]=2.52164453e-01;
  cumulativeDist[2][4][24]=6.06153846e-01;
  X[2][4][24]=3.38670030e-01;
  cumulativeDist[2][4][25]=6.30769253e-01;
  X[2][4][25]=4.02811319e-01;
  cumulativeDist[2][4][26]=6.55384600e-01;
  X[2][4][26]=4.66221198e-01;
  cumulativeDist[2][4][27]=6.80000007e-01;
  X[2][4][27]=5.28568745e-01;
  cumulativeDist[2][4][28]=7.04615414e-01;
  X[2][4][28]=5.85216463e-01;
  cumulativeDist[2][4][29]=7.29230762e-01;
  X[2][4][29]=6.61255121e-01;
  cumulativeDist[2][4][30]=7.53846169e-01;
  X[2][4][30]=7.35652804e-01;
  cumulativeDist[2][4][31]=7.78461516e-01;
  X[2][4][31]=8.18308890e-01;
  cumulativeDist[2][4][32]=8.03076923e-01;
  X[2][4][32]=8.91546190e-01;
  cumulativeDist[2][4][33]=8.27692330e-01;
  X[2][4][33]=9.69903409e-01;
  cumulativeDist[2][4][34]=8.52307677e-01;
  X[2][4][34]=1.06344301e+00;
  cumulativeDist[2][4][35]=8.76923084e-01;
  X[2][4][35]=1.12834221e+00;
  cumulativeDist[2][4][36]=9.01538491e-01;
  X[2][4][36]=1.24863958e+00;
  cumulativeDist[2][4][37]=9.26153839e-01;
  X[2][4][37]=1.42544186e+00;
  cumulativeDist[2][4][38]=9.50769246e-01;
  X[2][4][38]=1.60050255e+00;
  cumulativeDist[2][4][39]=9.75384593e-01;
  X[2][4][39]=1.83219439e+00;
  cumulativeDist[2][4][40]=1.00000000e+00;
  X[2][4][40]=2.32428628e+00;
    xMin[3][4]=-2.75335634e+00;
    xMax[3][4]=2.09552193e+00;
  cumulativeDist[3][4][0]=1.78461540e-02;
  X[3][4][0]=-2.75335634e+00;
  cumulativeDist[3][4][1]=3.99999991e-02;
  X[3][4][1]=-2.38598132e+00;
  cumulativeDist[3][4][2]=6.44615367e-02;
  X[3][4][2]=-1.88212276e+00;
  cumulativeDist[3][4][3]=8.92307684e-02;
  X[3][4][3]=-1.63438404e+00;
  cumulativeDist[3][4][4]=1.13846153e-01;
  X[3][4][4]=-1.43788201e+00;
  cumulativeDist[3][4][5]=1.38461545e-01;
  X[3][4][5]=-1.30811739e+00;
  cumulativeDist[3][4][6]=1.63076922e-01;
  X[3][4][6]=-1.20911252e+00;
  cumulativeDist[3][4][7]=1.87692314e-01;
  X[3][4][7]=-1.09236097e+00;
  cumulativeDist[3][4][8]=2.12307692e-01;
  X[3][4][8]=-1.00091797e+00;
  cumulativeDist[3][4][9]=2.36923084e-01;
  X[3][4][9]=-9.49982703e-01;
  cumulativeDist[3][4][10]=2.61538476e-01;
  X[3][4][10]=-8.75442594e-01;
  cumulativeDist[3][4][11]=2.86153853e-01;
  X[3][4][11]=-7.84391224e-01;
  cumulativeDist[3][4][12]=3.10769230e-01;
  X[3][4][12]=-7.07601219e-01;
  cumulativeDist[3][4][13]=3.35384607e-01;
  X[3][4][13]=-6.31876588e-01;
  cumulativeDist[3][4][14]=3.60000014e-01;
  X[3][4][14]=-5.74796736e-01;
  cumulativeDist[3][4][15]=3.84615391e-01;
  X[3][4][15]=-5.37356198e-01;
  cumulativeDist[3][4][16]=4.09230769e-01;
  X[3][4][16]=-4.93772015e-01;
  cumulativeDist[3][4][17]=4.33846146e-01;
  X[3][4][17]=-4.42706078e-01;
  cumulativeDist[3][4][18]=4.58461553e-01;
  X[3][4][18]=-3.89271066e-01;
  cumulativeDist[3][4][19]=4.83076930e-01;
  X[3][4][19]=-3.03686559e-01;
  cumulativeDist[3][4][20]=5.07692337e-01;
  X[3][4][20]=-2.10595950e-01;
  cumulativeDist[3][4][21]=5.32307684e-01;
  X[3][4][21]=-1.26002993e-01;
  cumulativeDist[3][4][22]=5.56923091e-01;
  X[3][4][22]=-3.67572517e-02;
  cumulativeDist[3][4][23]=5.81538439e-01;
  X[3][4][23]=2.25768643e-02;
  cumulativeDist[3][4][24]=6.06153846e-01;
  X[3][4][24]=7.25884009e-02;
  cumulativeDist[3][4][25]=6.30769253e-01;
  X[3][4][25]=1.53935809e-01;
  cumulativeDist[3][4][26]=6.55384600e-01;
  X[3][4][26]=2.83362217e-01;
  cumulativeDist[3][4][27]=6.80000007e-01;
  X[3][4][27]=4.07267079e-01;
  cumulativeDist[3][4][28]=7.04615414e-01;
  X[3][4][28]=4.83248398e-01;
  cumulativeDist[3][4][29]=7.29230762e-01;
  X[3][4][29]=5.52525163e-01;
  cumulativeDist[3][4][30]=7.53846169e-01;
  X[3][4][30]=6.15204245e-01;
  cumulativeDist[3][4][31]=7.78461516e-01;
  X[3][4][31]=6.67252064e-01;
  cumulativeDist[3][4][32]=8.03076923e-01;
  X[3][4][32]=7.52266616e-01;
  cumulativeDist[3][4][33]=8.27692330e-01;
  X[3][4][33]=8.79302531e-01;
  cumulativeDist[3][4][34]=8.52307677e-01;
  X[3][4][34]=9.86921132e-01;
  cumulativeDist[3][4][35]=8.76923084e-01;
  X[3][4][35]=1.05635017e+00;
  cumulativeDist[3][4][36]=9.01538491e-01;
  X[3][4][36]=1.15092731e+00;
  cumulativeDist[3][4][37]=9.26153839e-01;
  X[3][4][37]=1.26083940e+00;
  cumulativeDist[3][4][38]=9.50769246e-01;
  X[3][4][38]=1.40871090e+00;
  cumulativeDist[3][4][39]=9.75384593e-01;
  X[3][4][39]=1.59467834e+00;
  cumulativeDist[3][4][40]=1.00000000e+00;
  X[3][4][40]=2.09552193e+00;
}

//_______________________________________________________________________
inline void ReadPyKeras::Transform_2( std::vector<double>& iv, int clsIn) const
{
   // Gauss/Uniform transformation
   int cls=clsIn;
   if (cls < 0 || cls > 4) {
       if (4 > 1 ) cls = 4;
       else cls = 2;
   }
   // copy the variables which are going to be transformed                                

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
   }

   static std::vector<double> dv;                                                          
   dv.resize(nvar);                                                                       
   for (int ivar=0; ivar<nvar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];                
                                                                                          
   bool FlatNotGauss = false;                          
   double cumulant;                                                                       
   //const int nvar = 4;                                                         
   for (int ivar=0; ivar<nvar; ivar++) {                                                  
      int nbin  = nbins[ivar][cls];                                                       
      int ibin=0;                                                                         
      while (dv[ivar] > X[ivar][cls][ibin]) ibin++;                                       
                                                                                          
      if (ibin<0) { ibin=0;}                                                              
      if (ibin>=nbin) { ibin=nbin-1;}                                                     
      int nextbin = ibin;                                                                 
      if ((dv[ivar] > X[ivar][cls][ibin] && ibin !=nbin-1) || ibin==0)                    
         nextbin++;                                                                       
      else                                                                                
         nextbin--;                                                                       
                                                                                          
      double dx = X[ivar][cls][ibin]- X[ivar][cls][nextbin];                              
      double dy = cumulativeDist[ivar][cls][ibin] - cumulativeDist[ivar][cls][nextbin];   
      cumulant = cumulativeDist[ivar][cls][ibin] + (dv[ivar] - X[ivar][cls][ibin])* dy/dx;
                                                                                          
                                                                                          
      if (cumulant>1.-10e-10) cumulant = 1.-10e-10;                                       
      if (cumulant<10e-10)    cumulant = 10e-10;                                          
      if (FlatNotGauss) dv[ivar] = cumulant;                                              
      else {                                                                              
         double maxErfInvArgRange = 0.99999999;                                           
         double arg = 2.0*cumulant - 1.0;                                                 
         if (arg >  maxErfInvArgRange) arg= maxErfInvArgRange;                            
         if (arg < -maxErfInvArgRange) arg=-maxErfInvArgRange;                            
         double inverf=0., stp=1. ;                                                       
         while (stp >1.e-10){;                                                            
            if (erf(inverf)>arg) inverf -=stp ;                                           
            else if (erf(inverf)<=arg && erf(inverf+stp)>=arg) stp=stp/5. ;               
            else inverf += stp;                                                           
         } ;                                                                              
         //dv[ivar] = 1.414213562*TMath::ErfInverse(arg);                                 
         dv[ivar] = 1.414213562* inverf;                                                  
      }                                                                                   
   }                                                                                      
   // copy the transformed variables back                                                 
   for (int ivar=0; ivar<nvar; ivar++) iv[indicesPut.at(ivar)] = dv[ivar];                
}                                                                                         

//_______________________________________________________________________
inline void ReadPyKeras::InitTransform()
{
   InitTransform_1();
   InitTransform_2();
}

//_______________________________________________________________________
inline void ReadPyKeras::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
   Transform_2( iv, sigOrBgd );
}
